// ComponentInfoGenerator.cs
// Proyecto: CdCSharp.BlazorUI.Generator  (netstandard2.0)
//
// PIPELINE OVERVIEW
// ─────────────────────────────────────────────────────────────────────────────
//  1. Lee todos los .razor como AdditionalFiles (texto plano).
//  2. Para cada .razor extrae: @namespace · @inherits · @attribute y el @code.
//  3. Parsea el @code con CSharpSyntaxTree (es C# puro) para obtener
//     [Parameter] + XML docs + default values.
//  4. Sólo los que tienen @attribute [GenerateComponentInfo] generan salida.
//  5. Resolución de herencia:
//       padre .razor → busca en el mapa de todos los .razor parseados
//       padre .cs    → busca en la Compilation de Roslyn (GetSymbolsWithName)
//       .cs → .cs   → sube BaseType en Roslyn sin límite hasta object
// ─────────────────────────────────────────────────────────────────────────────

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Xml;
using System.Xml.Linq;

namespace CdCSharp.BlazorUI.Generator;

// ─────────────────────────────────────────────────────────────
//  Data models
// ─────────────────────────────────────────────────────────────

internal sealed record ParameterData(
    string Name,
    string Type,
    string? Default,
    string? Description);

internal sealed record ComponentData(
    string Namespace,
    string ComponentName,
    IReadOnlyList<ParameterData> Parameters);

/// <summary>Toda la información extraída de un único archivo .razor.</summary>
internal sealed record RazorFileData(
    string FilePath,
    string ComponentName,        // del nombre de archivo
    string? DeclaredNamespace,    // de @namespace
    string? InheritsRaw,          // de @inherits (texto en crudo)
    IReadOnlyList<ParameterData> OwnParameters,        // [Parameter] propios del @code
    bool GenerateInfo);        // true si @attribute [GenerateComponentInfo]

// ─────────────────────────────────────────────────────────────
//  Shared sources — se inyectan en la compilación de BlazorUI
// ─────────────────────────────────────────────────────────────

internal static class SharedSources
{
    public const string GenerateComponentInfoAttribute =
        """
        // <auto-generated/>
        namespace CdCSharp.BlazorUI;

        /// <summary>
        /// Marks a Blazor component for automatic documentation generation.
        /// Add <c>@attribute [GenerateComponentInfo]</c> to the .razor file,
        /// or <c>[GenerateComponentInfo]</c> to a .cs component class.
        /// </summary>
        [System.AttributeUsage(System.AttributeTargets.Class,
            AllowMultiple = false, Inherited = false)]
        public sealed class GenerateComponentInfoAttribute : System.Attribute { }
        """;

    // Mismo namespace que el atributo → un solo "using CdCSharp.BlazorUI;" en los generados.
    public const string ComponentParameterInfo =
        """
        // <auto-generated/>
        #nullable enable

        namespace CdCSharp.BlazorUI;

        /// <summary>Describes a single Blazor component parameter.</summary>
        public sealed record ComponentParameterInfo(
            string  ParameterName,
            string  ParameterType,
            string? ParameterDefault,
            string? ParameterDescription);
        """;
}

// ─────────────────────────────────────────────────────────────
//  Generator
// ─────────────────────────────────────────────────────────────

[Generator]
public sealed class ComponentInfoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Inyectar el atributo y el DTO compartido en la compilación destino.
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("GenerateComponentInfoAttribute.g.cs",
                SourceText.From(SharedSources.GenerateComponentInfoAttribute, Encoding.UTF8));
            ctx.AddSource("ComponentParameterInfo.g.cs",
                SourceText.From(SharedSources.ComponentParameterInfo, Encoding.UTF8));
        });

        // 2. Parsear TODOS los .razor como AdditionalFiles.
        //    Se necesitan todos para resolver cadenas de herencia entre .razor.
        IncrementalValueProvider<ImmutableArray<RazorFileData>> allRazorFiles = context.AdditionalTextsProvider
            .Where(static f => f.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) => RazorParser.Parse(file, ct))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!)          // assert non-null para tipar el provider
            .Collect();                             // ImmutableArray<RazorFileData>

        // 3. Combinar con la Compilation para resolver bases .cs.
        IncrementalValueProvider<(ImmutableArray<RazorFileData> Left, Compilation Right)> combined = allRazorFiles.Combine(context.CompilationProvider);

        // 4. Emitir un *ComponentInfo.g.cs por cada componente marcado.
        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            (ImmutableArray<RazorFileData> razorFiles, Compilation? compilation) = pair;

            // Mapa nombre simple → datos del .razor.
            // En caso de colisión de nombre (misma clase en distintas carpetas)
            // gana el primero encontrado; ese escenario es un error de diseño del proyecto.
            Dictionary<string, RazorFileData> razorMap = new(StringComparer.Ordinal);
            foreach (RazorFileData? f in razorFiles)
            {
                if (!razorMap.ContainsKey(f.ComponentName))
                    razorMap.Add(f.ComponentName, f);
            }

            foreach (RazorFileData? razorData in razorFiles)
            {
                if (!razorData.GenerateInfo) continue;

                IReadOnlyList<ParameterData> allParams = InheritanceResolver.Resolve(razorData, razorMap, compilation);
                string ns = razorData.DeclaredNamespace ?? "CdCSharp.BlazorUI.Components";
                ComponentData data = new(ns, razorData.ComponentName, allParams);

                spc.AddSource(
                    $"{razorData.ComponentName}ComponentInfo.g.cs",
                    SourceText.From(Emitter.Emit(data), Encoding.UTF8));
            }
        });
    }
}

// ─────────────────────────────────────────────────────────────
//  RazorParser — extrae datos de un archivo .razor
// ─────────────────────────────────────────────────────────────

internal static class RazorParser
{
    private static readonly Regex s_nsRx =
        new(@"@namespace\s+(\S+)", RegexOptions.Compiled);

    // @inherits puede incluir genéricos: BUIVariantComponentBase<BUIButton, BUIButtonVariant>
    private static readonly Regex s_inheritsRx =
        new(@"@inherits\s+([^\r\n]+)", RegexOptions.Compiled);

    private static readonly Regex s_generateRx =
        new(@"@attribute\s+\[GenerateComponentInfo\]", RegexOptions.Compiled);

    private static readonly Regex s_codeStartRx =
        new(@"@code\s*\{", RegexOptions.Compiled);

    private static readonly CSharpParseOptions s_parseOptions =
        CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Latest);

    // ── Punto de entrada ─────────────────────────────────────

    public static RazorFileData? Parse(AdditionalText file, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        string? text = file.GetText(ct)?.ToString();
        if (string.IsNullOrEmpty(text)) return null;

        string fileName = System.IO.Path.GetFileNameWithoutExtension(file.Path);
        string? ns = s_nsRx.Match(text!) is { Success: true } nm ? nm.Groups[1].Value.Trim() : null;
        string? inheritsRaw = s_inheritsRx.Match(text!) is { Success: true } im ? im.Groups[1].Value.Trim() : null;
        bool generateInfo = s_generateRx.IsMatch(text!);
        IReadOnlyList<ParameterData> ownParams = ParseCodeBlock(text!, ct);

        return new RazorFileData(
            FilePath: file.Path,
            ComponentName: fileName,
            DeclaredNamespace: ns,
            InheritsRaw: inheritsRaw,
            OwnParameters: ownParams,
            GenerateInfo: generateInfo);
    }

    // ── Parseo del bloque @code { } ──────────────────────────

    private static IReadOnlyList<ParameterData> ParseCodeBlock(string razorText, CancellationToken ct)
    {
        string? codeContent = ExtractCodeBlock(razorText);
        if (codeContent is null) return Array.Empty<ParameterData>();

        // Envolvemos en una clase temporal: el bloque @code es C# puro, Roslyn lo parsea
        // perfectamente. Los usings hacen que los identificadores de atributo se resuelvan.
        string wrappedSource =
            "#nullable enable\n" +
            "using System;\n" +
            "using Microsoft.AspNetCore.Components;\n" +
            $"partial class __Temp__ {{\n{codeContent}\n}}";

        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(wrappedSource, s_parseOptions, cancellationToken: ct);
        CompilationUnitSyntax root = syntaxTree.GetCompilationUnitRoot(ct);

        ClassDeclarationSyntax? classDecl = root.DescendantNodes()
                             .OfType<ClassDeclarationSyntax>()
                             .FirstOrDefault();

        if (classDecl is null) return Array.Empty<ParameterData>();

        List<ParameterData> result = new();
        foreach (PropertyDeclarationSyntax prop in classDecl.Members.OfType<PropertyDeclarationSyntax>())
        {
            if (!IsParameterProperty(prop)) continue;

            result.Add(new ParameterData(
                Name: prop.Identifier.Text,
                Type: prop.Type.ToString(),
                Default: prop.Initializer?.Value.ToString(),
                Description: XmlSummary(prop)));
        }

        return result;
    }

    /// <summary>
    /// Extrae el contenido del bloque @code { } usando conteo de profundidad de llaves.
    /// Maneja strings, chars y comentarios para evitar recuentos erróneos.
    /// </summary>
    private static string? ExtractCodeBlock(string content)
    {
        Match match = s_codeStartRx.Match(content);
        if (!match.Success) return null;

        // Posición de la llave '{' de apertura del @code
        int openBrace = match.Index + match.Length - 1;
        int depth = 0;
        bool inLineComment = false;
        bool inBlockComment = false;
        bool inString = false;
        bool inChar = false;
        char prev = '\0';

        for (int i = openBrace; i < content.Length; i++)
        {
            char c = content[i];

            // Comentario de línea ( // )
            if (!inString && !inChar && !inBlockComment && prev == '/' && c == '/')
                inLineComment = true;
            if (inLineComment && c == '\n')
                inLineComment = false;
            if (inLineComment) { prev = c; continue; }

            // Comentario de bloque ( /* */ )
            if (!inString && !inChar && !inLineComment && prev == '/' && c == '*')
                inBlockComment = true;
            if (inBlockComment && prev == '*' && c == '/')
            { inBlockComment = false; prev = c; continue; }
            if (inBlockComment) { prev = c; continue; }

            // String literal
            if (!inChar && c == '"' && prev != '\\')
                inString = !inString;

            // Char literal
            if (!inString && c == '\'' && prev != '\\')
                inChar = !inChar;

            if (!inString && !inChar)
            {
                if (c == '{') depth++;
                else if (c == '}')
                {
                    depth--;
                    if (depth == 0)
                        return content.Substring(openBrace + 1, i - openBrace - 1);
                }
            }

            prev = c;
        }

        return null; // @code sin cerrar (archivo malformado)
    }

    // ── Helpers de sintaxis ──────────────────────────────────

    private static bool IsParameterProperty(PropertyDeclarationSyntax prop)
    {
        foreach (AttributeListSyntax attrList in prop.AttributeLists)
            foreach (AttributeSyntax attr in attrList.Attributes)
            {
                string name = attr.Name.ToString();
                if (name is "Parameter" or "ParameterAttribute")
                    return true;
            }
        return false;
    }

    private static string? XmlSummary(PropertyDeclarationSyntax prop)
    {
        foreach (SyntaxTrivia trivia in prop.GetLeadingTrivia())
        {
            if (!trivia.HasStructure) continue;
            if (trivia.GetStructure() is not DocumentationCommentTriviaSyntax doc) continue;

            foreach (XmlNodeSyntax node in doc.Content)
            {
                if (node is not XmlElementSyntax el) continue;
                if (el.StartTag.Name.ToString() != "summary") continue;

                StringBuilder raw = new();
                foreach (XmlNodeSyntax cn in el.Content)
                    raw.Append(cn.ToString());

                // Quitar tags XML inline (<c>, <see cref="…"/>, etc.)
                string text = Regex.Replace(raw.ToString(), @"<[^>]+>", string.Empty);
                // Colapsar whitespace de summaries multilínea
                text = Regex.Replace(text, @"\s+", " ").Trim();

                return string.IsNullOrWhiteSpace(text) ? null : text;
            }
        }
        return null;
    }
}

// ─────────────────────────────────────────────────────────────
//  InheritanceResolver — recorre la cadena de herencia completa
// ─────────────────────────────────────────────────────────────

internal static class InheritanceResolver
{
    /// <summary>
    /// Devuelve todos los [Parameter] del componente (propios + heredados), en orden:
    /// primero los del tipo más derivado, luego los de sus bases sucesivas.
    ///
    /// Reglas de deduplicación:
    ///   Si un nombre ya aparece en una clase hija, se descarta en las clases padre.
    ///
    /// Cadenas soportadas:
    ///   .razor → .razor → .razor → …
    ///   .razor → .cs → .cs → …
    ///   (mezcla) .razor → .razor → .cs → .cs → …
    /// </summary>
    public static IReadOnlyList<ParameterData> Resolve(
        RazorFileData root,
        Dictionary<string, RazorFileData> razorMap,
        Compilation compilation)
    {
        List<ParameterData> result = new();
        HashSet<string> seen = new(StringComparer.Ordinal);
        HashSet<string> visited = new(StringComparer.Ordinal); // protección anti-ciclo

        CollectFromRazor(root, razorMap, compilation, seen, result, visited);
        return result;
    }

    // ── Recolección desde un nodo .razor ────────────────────

    private static void CollectFromRazor(
        RazorFileData component,
        Dictionary<string, RazorFileData> razorMap,
        Compilation compilation,
        HashSet<string> seen,
        List<ParameterData> result,
        HashSet<string> visited)
    {
        if (!visited.Add(component.ComponentName)) return; // anti-ciclo

        // 1. Parámetros propios (en orden de declaración en el @code)
        foreach (ParameterData p in component.OwnParameters)
            if (seen.Add(p.Name))
                result.Add(p);

        // 2. Resolver base
        if (component.InheritsRaw is null) return;

        string baseName = ExtractSimpleName(component.InheritsRaw);

        if (razorMap.TryGetValue(baseName, out RazorFileData? baseRazor))
        {
            // La base es otro .razor → seguir por la rama Razor
            CollectFromRazor(baseRazor, razorMap, compilation, seen, result, visited);
        }
        else
        {
            // La base es un tipo .cs → cambiar a la rama Roslyn
            CollectFromCompilation(baseName, compilation, seen, result);
        }
    }

    // ── Recolección desde un nodo .cs (Roslyn) ──────────────

    private static void CollectFromCompilation(
        string typeName,
        Compilation compilation,
        HashSet<string> seen,
        List<ParameterData> result)
    {
        INamedTypeSymbol? symbol = FindType(compilation, typeName);
        if (symbol is null) return;

        // Sube la jerarquía .cs completa hasta llegar a un tipo especial (object, etc.)
        INamedTypeSymbol? current = symbol;
        while (current is { SpecialType: SpecialType.None })
        {
            foreach (IPropertySymbol member in current.GetMembers().OfType<IPropertySymbol>())
            {
                if (!seen.Add(member.Name)) continue;
                if (!IsParameter(member)) continue;

                result.Add(new ParameterData(
                    Name: member.Name,
                    Type: TypeString(member),
                    Default: DefaultValue(member),
                    Description: XmlSummaryFromSymbol(member)));
            }

            current = current.BaseType;
        }
    }

    // ── Helpers ──────────────────────────────────────────────

    /// <summary>
    /// Extrae el nombre simple a partir del texto en crudo del @inherits.
    ///
    ///   "BUIVariantComponentBase&lt;BUIButton, BUIButtonVariant&gt;" → "BUIVariantComponentBase"
    ///   "CdCSharp.BlazorUI.Components.BUIBase"                       → "BUIBase"
    ///   "BUIBase"                                                     → "BUIBase"
    /// </summary>
    private static string ExtractSimpleName(string inheritsRaw)
    {
        string name = inheritsRaw.Trim();

        // Quitar genéricos
        int genericIdx = name.IndexOf('<');
        if (genericIdx > 0) name = name.Substring(0, genericIdx);

        // Quitar namespace
        int dotIdx = name.LastIndexOf('.');
        if (dotIdx >= 0) name = name.Substring(dotIdx + 1);

        return name.Trim();
    }

    /// <summary>
    /// Búsqueda por nombre simple en toda la compilación.
    /// Funciona sin conocer el namespace de la clase base.
    /// </summary>
    private static INamedTypeSymbol? FindType(Compilation compilation, string simpleName) =>
        compilation
            .GetSymbolsWithName(name => name == simpleName, SymbolFilter.Type)
            .OfType<INamedTypeSymbol>()
            .FirstOrDefault();

    private static bool IsParameter(IPropertySymbol prop)
    {
        foreach (AttributeData attr in prop.GetAttributes())
            if (attr.AttributeClass?.Name == "ParameterAttribute")
                return true;
        return false;
    }

    private static readonly SymbolDisplayFormat s_typeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameOnly,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static string TypeString(IPropertySymbol prop) =>
        prop.Type.ToDisplayString(s_typeFormat);

    private static string? DefaultValue(IPropertySymbol prop)
    {
        foreach (SyntaxReference syntaxRef in prop.DeclaringSyntaxReferences)
            if (syntaxRef.GetSyntax() is PropertyDeclarationSyntax { Initializer.Value: { } v })
                return v.ToString();
        return null;
    }

    private static string? XmlSummaryFromSymbol(IPropertySymbol prop)
    {
        // Primary source: Roslyn's built-in extraction. Works across assemblies — if the referenced
        // assembly ships its .xml alongside the DLL, the summary comes through without syntax refs.
        string? documentationXml = prop.GetDocumentationCommentXml();
        if (!string.IsNullOrWhiteSpace(documentationXml))
        {
            string? parsed = ExtractSummaryFromDocXml(documentationXml!);
            if (!string.IsNullOrWhiteSpace(parsed))
                return parsed;
        }

        // Fallback: declaring-syntax trivia. Only reachable for symbols declared in the current
        // compilation whose GetDocumentationCommentXml returned empty (e.g. broken XML).
        foreach (SyntaxReference syntaxRef in prop.DeclaringSyntaxReferences)
        {
            SyntaxNode syntax = syntaxRef.GetSyntax();
            foreach (SyntaxTrivia trivia in syntax.GetLeadingTrivia())
            {
                if (!trivia.HasStructure) continue;
                if (trivia.GetStructure() is not DocumentationCommentTriviaSyntax doc) continue;

                foreach (XmlNodeSyntax node in doc.Content)
                {
                    if (node is not XmlElementSyntax el) continue;
                    if (el.StartTag.Name.ToString() != "summary") continue;

                    StringBuilder raw = new();
                    foreach (XmlNodeSyntax cn in el.Content) raw.Append(cn.ToString());

                    string text = Regex.Replace(raw.ToString(), @"<[^>]+>", string.Empty);
                    text = Regex.Replace(text, @"\s+", " ").Trim();
                    return string.IsNullOrWhiteSpace(text) ? null : text;
                }
            }
        }
        return null;
    }

    private static string? ExtractSummaryFromDocXml(string xml)
    {
        try
        {
            // Roslyn wraps the summary in <member name="...">…</member>. Parse and pick <summary>.
            XDocument doc = XDocument.Parse(xml, LoadOptions.PreserveWhitespace);
            XElement? summary = doc.Root?.Element("summary");
            if (summary == null) return null;

            StringBuilder sb = new();
            FlattenDocNode(summary, sb);
            string text = Regex.Replace(sb.ToString(), @"\s+", " ").Trim();
            return string.IsNullOrWhiteSpace(text) ? null : text;
        }
        catch (XmlException)
        {
            return null;
        }
    }

    private static void FlattenDocNode(XNode node, StringBuilder sb)
    {
        switch (node)
        {
            case XText text:
                sb.Append(text.Value);
                break;
            case XElement el:
                switch (el.Name.LocalName)
                {
                    case "see":
                    case "seealso":
                        string? cref = el.Attribute("cref")?.Value;
                        string? langword = el.Attribute("langword")?.Value;
                        if (cref != null)
                        {
                            // Roslyn prefixes the cref with the member kind ("T:", "P:", "M:", ...). Strip it
                            // and keep only the last dotted segment so links collapse to a bare identifier.
                            int colon = cref.IndexOf(':');
                            string target = colon >= 0 ? cref.Substring(colon + 1) : cref;
                            int lastDot = target.LastIndexOf('.');
                            sb.Append(lastDot >= 0 ? target.Substring(lastDot + 1) : target);
                        }
                        else if (langword != null)
                        {
                            sb.Append(langword);
                        }
                        break;
                    default:
                        // <c>, <para>, <paramref>, unknown → recurse. Drops the surrounding tag, keeps text.
                        foreach (XNode child in el.Nodes())
                            FlattenDocNode(child, sb);
                        break;
                }
                break;
        }
    }
}

// ─────────────────────────────────────────────────────────────
//  Emitter — genera el string C# del archivo *ComponentInfo.g.cs
// ─────────────────────────────────────────────────────────────

internal static class Emitter
{
    public static string Emit(ComponentData data)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using CdCSharp.BlazorUI;");
        sb.AppendLine();
        sb.AppendLine($"namespace {data.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated parameter docs for <see cref=\"{data.ComponentName}\"/>.</summary>");
        sb.AppendLine($"public static partial class {data.ComponentName}ComponentInfo");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly ComponentParameterInfo[] Parameters =");
        sb.AppendLine("    [");

        foreach (ParameterData p in data.Parameters)
        {
            sb.AppendLine("        new(");
            sb.AppendLine($"            ParameterName:        \"{p.Name}\",");
            sb.AppendLine($"            ParameterType:        \"{p.Type}\",");
            sb.AppendLine($"            ParameterDefault:     {Literal(p.Default)},");
            sb.AppendLine($"            ParameterDescription: {Literal(p.Description)}");
            sb.AppendLine("        ),");
        }

        sb.AppendLine("    ];");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Literal(string? value) =>
        value is null
            ? "null"
            : $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
}