using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CdCSharp.BlazorUI.Docs.CodeGeneration;

[Generator]
public sealed class DocDemoGenerator : IIncrementalGenerator
{
    private static readonly Regex OpenTag = new(
        @"<DocDemo\b([^>]*?)(/?)>",
        RegexOptions.Compiled | RegexOptions.Singleline);

    private static readonly Regex CloseTag = new(
        @"</DocDemo\s*>",
        RegexOptions.Compiled);

    private static readonly Regex KeyAttr = new(
        @"Key\s*=\s*""([^""]+)""",
        RegexOptions.Compiled);

    private static readonly Regex NamespaceDirective = new(
        @"(?m)^\s*@namespace\s+([\w.]+)\s*$",
        RegexOptions.Compiled);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<(string? RootNamespace, string? ProjectDir)> globals =
            context.AnalyzerConfigOptionsProvider.Select((p, _) =>
            {
                p.GlobalOptions.TryGetValue("build_property.rootnamespace", out string? rootNs);
                p.GlobalOptions.TryGetValue("build_property.projectdir", out string? projectDir);
                return (rootNs, projectDir);
            });

        IncrementalValuesProvider<RazorInput> files = context.AdditionalTextsProvider
            .Where(t => t.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
            .Combine(globals)
            .Select((pair, ct) =>
            {
                SourceText? src = pair.Left.GetText(ct);
                return new RazorInput(
                    pair.Left.Path,
                    src?.ToString() ?? string.Empty,
                    pair.Right.RootNamespace,
                    pair.Right.ProjectDir);
            })
            .Where(x => x.Text.Length > 0);

        context.RegisterSourceOutput(files, Emit);
    }

    private static void Emit(SourceProductionContext ctx, RazorInput input)
    {
        List<DemoBlock> demos = Parse(input.Text);
        if (demos.Count == 0)
            return;

        (string ns, string cls)? target = ResolveTarget(input);
        if (target is null)
            return;

        (string ns, string cls) = target.Value;

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("partial class ").AppendLine(cls);
        sb.AppendLine("{");
        sb.AppendLine("    internal static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, string> __DocDemoCodes");
        sb.AppendLine("        = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal)");
        sb.AppendLine("        {");
        foreach (DemoBlock d in demos)
        {
            sb.Append("            [\"")
              .Append(EscapeLiteral(d.Key))
              .Append("\"] = \"")
              .Append(EscapeLiteral(d.Code))
              .AppendLine("\",");
        }
        sb.AppendLine("        };");
        sb.AppendLine("}");

        string hint = $"{ns.Replace('.', '_')}_{cls}.DocDemos.g.cs";
        ctx.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static (string Namespace, string Class)? ResolveTarget(RazorInput input)
    {
        string className = GetFileNameWithoutExtension(input.Path);
        if (string.IsNullOrEmpty(className))
            return null;

        Match nsMatch = NamespaceDirective.Match(input.Text);
        if (nsMatch.Success)
            return (nsMatch.Groups[1].Value, className);

        if (string.IsNullOrEmpty(input.RootNamespace) || string.IsNullOrEmpty(input.ProjectDir))
            return null;

        string dir = GetDirectoryName(input.Path);
        string projectDir = input.ProjectDir!.TrimEnd('\\', '/');

        if (dir.Length < projectDir.Length ||
            !dir.StartsWith(projectDir, StringComparison.OrdinalIgnoreCase))
            return null;

        string rel = dir.Substring(projectDir.Length).Trim('\\', '/');
        string ns = input.RootNamespace!;
        if (rel.Length > 0)
            ns += "." + rel.Replace('\\', '.').Replace('/', '.');

        return (ns, className);
    }

    private static string GetFileNameWithoutExtension(string path)
    {
        int slash = path.LastIndexOfAny(new[] { '\\', '/' });
        string name = slash < 0 ? path : path.Substring(slash + 1);
        int dot = name.LastIndexOf('.');
        return dot < 0 ? name : name.Substring(0, dot);
    }

    private static string GetDirectoryName(string path)
    {
        int slash = path.LastIndexOfAny(new[] { '\\', '/' });
        return slash < 0 ? string.Empty : path.Substring(0, slash);
    }

    private static List<DemoBlock> Parse(string src)
    {
        List<DemoBlock> result = new();

        List<(int Pos, int EndIndex, bool IsOpen, bool SelfClose, string Attrs)> events = new();

        foreach (Match m in OpenTag.Matches(src))
        {
            bool selfClose = m.Groups[2].Value == "/";
            events.Add((m.Index, m.Index + m.Length, true, selfClose, m.Groups[1].Value));
        }

        foreach (Match m in CloseTag.Matches(src))
            events.Add((m.Index, m.Index + m.Length, false, false, string.Empty));

        events.Sort((a, b) => a.Pos.CompareTo(b.Pos));

        int depth = 0;
        int topStart = -1;
        string? topKey = null;

        foreach ((int pos, int endIdx, bool isOpen, bool selfClose, string attrs) in events)
        {
            if (isOpen)
            {
                if (selfClose)
                    continue;

                if (depth == 0)
                {
                    Match keyM = KeyAttr.Match(attrs);
                    topKey = keyM.Success ? keyM.Groups[1].Value : null;
                    topStart = endIdx;
                }
                depth++;
            }
            else
            {
                if (depth == 0)
                    continue;

                depth--;
                if (depth == 0 && topKey is not null && topStart >= 0)
                {
                    string inner = src.Substring(topStart, pos - topStart);
                    result.Add(new DemoBlock(topKey, Dedent(inner)));
                    topKey = null;
                    topStart = -1;
                }
            }
        }

        return result;
    }

    private static string Dedent(string text)
    {
        string[] lines = text.Replace("\r\n", "\n").Split('\n');

        int start = 0;
        int end = lines.Length - 1;
        while (start <= end && string.IsNullOrWhiteSpace(lines[start])) start++;
        while (end >= start && string.IsNullOrWhiteSpace(lines[end])) end--;
        if (start > end) return string.Empty;

        int min = int.MaxValue;
        for (int i = start; i <= end; i++)
        {
            string l = lines[i];
            if (string.IsNullOrWhiteSpace(l)) continue;
            int j = 0;
            while (j < l.Length && (l[j] == ' ' || l[j] == '\t')) j++;
            if (j < min) min = j;
        }

        if (min == int.MaxValue) min = 0;

        StringBuilder sb = new();
        for (int i = start; i <= end; i++)
        {
            if (i > start) sb.Append('\n');
            string l = lines[i];
            if (min > 0 && l.Length >= min)
            {
                bool allWs = true;
                for (int k = 0; k < min; k++)
                    if (l[k] != ' ' && l[k] != '\t') { allWs = false; break; }
                sb.Append(allWs ? l.Substring(min) : l);
            }
            else
            {
                sb.Append(l);
            }
        }
        return sb.ToString();
    }

    private static string EscapeLiteral(string s)
    {
        StringBuilder sb = new(s.Length + 8);
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\r': sb.Append("\\r"); break;
                case '\n': sb.Append("\\n"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }

    private readonly record struct RazorInput(string Path, string Text, string? RootNamespace, string? ProjectDir);
    private readonly record struct DemoBlock(string Key, string Code);
}
