using CdCSharp.Theon.Models;
using System.Collections.Concurrent;

namespace CdCSharp.Theon.Infrastructure;

/// <summary>
/// Tracks files generated by each agent to maintain context across conversations
/// </summary>
public class GeneratedFilesTracker
{
    private readonly ConcurrentDictionary<string, List<GeneratedFileRecord>> _agentFiles = new();
    private readonly TheonLogger _logger;

    public GeneratedFilesTracker(TheonLogger logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Records files generated by an agent
    /// </summary>
    public void RecordFiles(string agentId, List<GeneratedFile> files)
    {
        if (files.Count == 0) return;

        List<GeneratedFileRecord> records = _agentFiles.GetOrAdd(agentId, _ => []);

        lock (records)
        {
            foreach (GeneratedFile file in files)
            {
                // Update existing or add new
                GeneratedFileRecord? existing = records.FirstOrDefault(r => r.FileName == file.FileName);

                if (existing != null)
                {
                    records.Remove(existing);
                    _logger.Debug($"Agent {agentId} updated file: {file.FileName}");
                }
                else
                {
                    _logger.Debug($"Agent {agentId} created file: {file.FileName}");
                }

                records.Add(new GeneratedFileRecord
                {
                    FileName = file.FileName,
                    Language = file.Language ?? "unknown",
                    ContentSize = file.Content.Length,
                    CreatedAt = DateTime.UtcNow,
                    LastModified = DateTime.UtcNow,
                    CurrentContent = file.Content
                });
            }
        }
    }

    /// <summary>
    /// Gets formatted list of files for an agent's context
    /// </summary>
    public string GetFilesContext(string agentId)
    {
        if (!_agentFiles.TryGetValue(agentId, out List<GeneratedFileRecord>? records))
            return "You haven't generated any files yet.";

        if (records.Count == 0)
            return "You haven't generated any files yet.";

        List<string> lines = ["## Files You've Generated", ""];

        lock (records)
        {
            foreach (GeneratedFileRecord record in records.OrderBy(r => r.FileName))
            {
                lines.Add($"- **{record.FileName}** ({record.Language})");
                lines.Add($"  - Size: {record.ContentSize:N0} characters");
                lines.Add($"  - Created: {record.CreatedAt:yyyy-MM-dd HH:mm:ss}");
                lines.Add($"  - Modified: {record.LastModified:yyyy-MM-dd HH:mm:ss}");
                lines.Add("");
            }
        }

        return string.Join("\n", lines);
    }

    /// <summary>
    /// Gets a specific file's content
    /// </summary>
    public string? GetFileContent(string agentId, string fileName)
    {
        if (!_agentFiles.TryGetValue(agentId, out List<GeneratedFileRecord>? records))
            return null;

        lock (records)
        {
            return records.FirstOrDefault(r => r.FileName.Equals(fileName, StringComparison.OrdinalIgnoreCase))?.CurrentContent;
        }
    }

    /// <summary>
    /// Gets all files for an agent
    /// </summary>
    public List<GeneratedFile> GetAllFiles(string agentId)
    {
        if (!_agentFiles.TryGetValue(agentId, out List<GeneratedFileRecord>? records))
            return [];

        lock (records)
        {
            return records.Select(r => new GeneratedFile
            {
                FileName = r.FileName,
                Language = r.Language,
                Content = r.CurrentContent
            }).ToList();
        }
    }

    /// <summary>
    /// Clears all files for an agent
    /// </summary>
    public void ClearFiles(string agentId)
    {
        if (_agentFiles.TryRemove(agentId, out List<GeneratedFileRecord>? records))
        {
            _logger.Debug($"Cleared {records.Count} files for agent {agentId}");
        }
    }

    /// <summary>
    /// Gets summary for session saving
    /// </summary>
    public Dictionary<string, List<GeneratedFileRecord>> GetAllRecords()
    {
        return _agentFiles.ToDictionary(kvp => kvp.Key, kvp => kvp.Value.ToList());
    }

    /// <summary>
    /// Restores files from session
    /// </summary>
    public void RestoreRecords(Dictionary<string, List<GeneratedFileRecord>> records)
    {
        _agentFiles.Clear();
        foreach ((string agentId, List<GeneratedFileRecord> files) in records)
        {
            _agentFiles[agentId] = [.. files];
            _logger.Debug($"Restored {files.Count} files for agent {agentId}");
        }
    }
}

/// <summary>
/// Record of a generated file
/// </summary>
public record GeneratedFileRecord
{
    public required string FileName { get; init; }
    public required string Language { get; init; }
    public required int ContentSize { get; init; }
    public DateTime CreatedAt { get; init; }
    public DateTime LastModified { get; init; }
    public required string CurrentContent { get; init; }
}