namespace CdCSharp.BlazorUI.SyntaxHighlight.Tokens;

public enum TokenType
{
    Text,
    Keyword,
    ControlKeyword,
    Type,
    String,
    VerbatimString,
    InterpolatedString,
    Char,
    Number,
    Comment,
    Operator,
    Punctuation,
    Method,
    Property,
    Field,
    Parameter,
    Variable,
    Namespace,
    Directive,
    PreprocessorDirective,
    Attribute,
    Tag,
    TagName,
    AttributeName,
    AttributeValue,
    CssSelector,
    CssProperty,
    CssValue,
    CssUnit,
    CssPseudo,
    RazorDelimiter,
    RazorExpression,
    RazorCodeBlock,
}