using CdCSharp.DocGen.Core.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text.RegularExpressions;

namespace CdCSharp.DocGen.Core.Scanning;

public interface IFileScanner
{
    bool CanScan(string filePath);
    Task<Models.FileInfo> ScanAsync(string filePath, string projectRoot);
}

public class CSharpScanner : IFileScanner
{
    public bool CanScan(string filePath) => filePath.EndsWith(".cs", StringComparison.OrdinalIgnoreCase);

    public async Task<Models.FileInfo> ScanAsync(string filePath, string projectRoot)
    {
        string code = await File.ReadAllTextAsync(filePath);
        SyntaxTree tree = CSharpSyntaxTree.ParseText(code);
        CompilationUnitSyntax root = tree.GetCompilationUnitRoot();

        List<string> symbols = [];
        SymbolWalker walker = new(symbols);
        walker.Visit(root);

        return new Models.FileInfo
        {
            RelativePath = Path.GetRelativePath(projectRoot, filePath),
            Type = FileType.CSharp,
            LineCount = code.Split('\n').Length,
            TokenEstimate = code.Length / 4,
            PublicSymbols = symbols,
            Importance = DetermineImportance(filePath, symbols, code)
        };
    }

    private static ImportanceLevel DetermineImportance(string path, List<string> symbols, string code)
    {
        if (code.Contains("<auto-generated>")) return ImportanceLevel.Low;
        if (path.Contains("SourceGenerator") || code.Contains("[Generator]")) return ImportanceLevel.Critical;
        if (path.Contains("Test", StringComparison.OrdinalIgnoreCase)) return ImportanceLevel.Low;
        if (symbols.Count > 5) return ImportanceLevel.High;
        return ImportanceLevel.Normal;
    }

    private class SymbolWalker(List<string> symbols) : CSharpSyntaxWalker
    {
        public override void VisitClassDeclaration(ClassDeclarationSyntax node)
        {
            if (IsPublic(node.Modifiers)) symbols.Add($"class {node.Identifier.Text}");
            base.VisitClassDeclaration(node);
        }

        public override void VisitInterfaceDeclaration(InterfaceDeclarationSyntax node)
        {
            if (IsPublic(node.Modifiers)) symbols.Add($"interface {node.Identifier.Text}");
            base.VisitInterfaceDeclaration(node);
        }

        public override void VisitRecordDeclaration(RecordDeclarationSyntax node)
        {
            if (IsPublic(node.Modifiers)) symbols.Add($"record {node.Identifier.Text}");
            base.VisitRecordDeclaration(node);
        }

        public override void VisitStructDeclaration(StructDeclarationSyntax node)
        {
            if (IsPublic(node.Modifiers)) symbols.Add($"struct {node.Identifier.Text}");
            base.VisitStructDeclaration(node);
        }

        public override void VisitEnumDeclaration(EnumDeclarationSyntax node)
        {
            if (IsPublic(node.Modifiers)) symbols.Add($"enum {node.Identifier.Text}");
            base.VisitEnumDeclaration(node);
        }

        private static bool IsPublic(SyntaxTokenList modifiers) =>
            modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword));
    }
}

public class RazorScanner : IFileScanner
{
    private static readonly Regex ParameterRegex = new(
        @"\[Parameter\]\s*(?:\[.*?\]\s*)*public\s+(\w+(?:<[^>]+>)?)\s+(\w+)",
        RegexOptions.Compiled);

    public bool CanScan(string filePath) => filePath.EndsWith(".razor", StringComparison.OrdinalIgnoreCase);

    public async Task<Models.FileInfo> ScanAsync(string filePath, string projectRoot)
    {
        string code = await File.ReadAllTextAsync(filePath);
        string componentName = Path.GetFileNameWithoutExtension(filePath);

        List<string> symbols = [$"component {componentName}"];

        foreach (Match match in ParameterRegex.Matches(code))
        {
            if (match.Groups.Count > 2)
                symbols.Add($"param {match.Groups[2].Value}:{match.Groups[1].Value}");
        }

        if (code.Contains("@code")) symbols.Add("@code");

        return new Models.FileInfo
        {
            RelativePath = Path.GetRelativePath(projectRoot, filePath),
            Type = FileType.Razor,
            LineCount = code.Split('\n').Length,
            TokenEstimate = code.Length / 4,
            PublicSymbols = symbols,
            Importance = code.Contains("@page") ? ImportanceLevel.High : ImportanceLevel.Normal
        };
    }
}

public class TypeScriptScanner : IFileScanner
{
    private static readonly Regex ExportFunctionRegex = new(@"export\s+(?:async\s+)?function\s+(\w+)", RegexOptions.Compiled);
    private static readonly Regex ExportClassRegex = new(@"export\s+class\s+(\w+)", RegexOptions.Compiled);
    private static readonly Regex ExportConstRegex = new(@"export\s+const\s+(\w+)", RegexOptions.Compiled);

    public bool CanScan(string filePath)
    {
        string ext = Path.GetExtension(filePath).ToLowerInvariant();
        return ext is ".ts" or ".tsx" or ".js" or ".jsx";
    }

    public async Task<Models.FileInfo> ScanAsync(string filePath, string projectRoot)
    {
        string code = await File.ReadAllTextAsync(filePath);
        List<string> symbols = [];

        foreach (Match m in ExportFunctionRegex.Matches(code))
            symbols.Add($"function {m.Groups[1].Value}");
        foreach (Match m in ExportClassRegex.Matches(code))
            symbols.Add($"class {m.Groups[1].Value}");
        foreach (Match m in ExportConstRegex.Matches(code))
            symbols.Add($"const {m.Groups[1].Value}");

        string ext = Path.GetExtension(filePath).ToLowerInvariant();
        FileType type = ext is ".ts" or ".tsx" ? FileType.TypeScript : FileType.JavaScript;

        return new Models.FileInfo
        {
            RelativePath = Path.GetRelativePath(projectRoot, filePath),
            Type = type,
            LineCount = code.Split('\n').Length,
            TokenEstimate = code.Length / 4,
            PublicSymbols = symbols,
            Importance = symbols.Count > 0 ? ImportanceLevel.Normal : ImportanceLevel.Low
        };
    }
}

public class CssScanner : IFileScanner
{
    private static readonly Regex VariableRegex = new(@"--[\w-]+\s*:", RegexOptions.Compiled);
    private static readonly Regex ClassRegex = new(@"\.[\w-]+\s*\{", RegexOptions.Compiled);

    public bool CanScan(string filePath)
    {
        string ext = Path.GetExtension(filePath).ToLowerInvariant();
        return ext is ".css" or ".scss";
    }

    public async Task<Models.FileInfo> ScanAsync(string filePath, string projectRoot)
    {
        string code = await File.ReadAllTextAsync(filePath);
        List<string> symbols = [];

        int varCount = VariableRegex.Matches(code).Count;
        int classCount = ClassRegex.Matches(code).Count;

        if (varCount > 0) symbols.Add($"{varCount} vars");
        if (classCount > 0) symbols.Add($"{classCount} classes");

        string ext = Path.GetExtension(filePath).ToLowerInvariant();
        bool isTheme = filePath.Contains("theme", StringComparison.OrdinalIgnoreCase) ||
                       (code.Contains(":root") && code.Contains("--"));

        return new Models.FileInfo
        {
            RelativePath = Path.GetRelativePath(projectRoot, filePath),
            Type = ext == ".scss" ? FileType.Scss : FileType.Css,
            LineCount = code.Split('\n').Length,
            TokenEstimate = code.Length / 4,
            PublicSymbols = symbols,
            Importance = isTheme ? ImportanceLevel.High : ImportanceLevel.Normal
        };
    }
}